.TH MX-PACKAGEINSTALLER 1 "July 2026" "MX Package Installer 26.07.2" "User Commands"
.SH NAME
mx-packageinstaller \- install and manage software packages
.SH SYNOPSIS
.B mx-packageinstaller
.RI [ options ]
.SH DESCRIPTION
.B mx-packageinstaller
is a graphical package-management application.
It installs and removes packages from your system's enabled repositories,
and can also manage Flatpak and Snap applications.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display command-line help and exit.
.TP
.B \-v, \-\-version
Display version information and exit.
.TP
.B \-s, \-\-skip\-online\-check
Skip the internet-availability check.
Use this when the check incorrectly reports that the system is offline.
.SH FILES
.TP
.I /var/log/mxpi.log
Log from the most recent operation.
.SH SEE ALSO
.BR flatpak (1),
.BR snap (8)
